name: Node.js CI
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Submodules
        run: git submodule update --init --recursive

      - name: Setup Node.js
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Generate code
        run: npm run codegen

      - name: Run linting
        run: npm run lint --if-present

      - name: Check code formatting
        run: npm run prettier:check --if-present

      - name: Run unit tests
        run: npm run test:unit

      - name: Build project
        run: npm run build --if-present

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            **/*test-results*
            **/*coverage*
          retention-days: 7
